# Generated by Django 3.2.3 on 2021-05-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_film_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(1, 'Horror'), (2, 'Sci=fi'), (3, 'Drama'), (4, 'Comedy'), (0, 'Undefined')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.extrainfo'),
        ),
    ]
