# Generated by Django 3.2.3 on 2021-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20210521_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.IntegerField(choices=[(2, 'Sci=fi'), (4, 'Comedy'), (0, 'Undefined'), (3, 'Drama'), (1, 'Horror')], default=0),
        ),
    ]
