# Generated by Django 3.2.3 on 2021-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_extrainfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.IntegerField(choices=[(3, 'Drama'), (0, 'Undefined'), (1, 'Horror'), (4, 'Comedy'), (2, 'Sci=fi')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
