# Generated by Django 3.2.3 on 2021-05-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_alter_extrainfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Undefined'), (4, 'Comedy'), (1, 'Horror'), (3, 'Drama'), (2, 'Sci=fi')], default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Api.film'),
        ),
    ]
