# Generated by Django 3.2.3 on 2021-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20210522_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.IntegerField(choices=[(4, 'Comedy'), (0, 'Undefined'), (2, 'Sci=fi'), (1, 'Horror'), (3, 'Drama')], default=0),
        ),
    ]
